# Workflow name.
name: Python application

# run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Check-out your repository.
      - uses: actions/checkout@v2
      - name: Build & Push Image
        run: |
          echo "${{ secrets.DOCKERPW }}" | docker login -u "kujo21" --password-stdin
          docker image build -t kujo21/hw2app:v1
          docker push kujo21/hw2app:v1 

